title:            Joerg's Repos
tagline:          Explain all my repos on Github.
description:      This site explains all my repos on Github and gives hints about how to use them.
canonical:        https://github.com/joergkrause

# Owner/author information
owner:
  name:           Joerg Krause
  avatar:         avatar.png
  bio:            "Geek & Pro"
  email:          joerg@krause.net
  twitter:        joergisageek
  github:         joergkrause
  location:       "Berlin, Germany"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/joergkrause
    external: true
  - title: JoergIsAGeek?
    url: http://joergkrause.de
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
